name: docker

on:
  pull_request:
    paths:
      - '.github/workflows/docker.yaml'
      - 'Dockerfile'
      - 'include/**'
      - 'libbpf/**'
      - 'src/**'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  dockerimage:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: recursive

      - name: Build bpftool container image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          push: false
          tags: bpftool:latest

      - name: Test bpftool container image
        run: |
          docker run --rm --privileged --pid=host bpftool version
          docker run --rm --privileged --pid=host bpftool prog
          docker run --rm --privileged --pid=host bpftool map

      - name: Lint Docker image
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: Dockerfile
